# Generated by Django 3.2 on 2021-08-15 21:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_rename_deliveryaddress_order_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('total_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
