# Generated by Django 3.2 on 2021-08-15 21:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('info', django.db.models.manager.Manager()),
            ],
        ),
    ]
